# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 19:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Format is: '+999999999'. You can enter upto 12 digits.", regex='^\\+?1?\\d{9,12}$')])),
                ('class_name', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Format is: '+999999999'. You can enter upto 12 digits.", regex='^\\+?1?\\d{9,12}$')])),
                ('type_flag', models.PositiveSmallIntegerField()),
                ('pin', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
