# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='is_verified',
        ),
    ]
